[general]
import = [
    "~/.config/alacritty/themes/gruvbox_dark.toml"
]

[env]
WINIT_X11_SCALE_FACTOR = "1.0"

[window]
# padding = { x = 10, y = 10 }
# opacity = 0.5

[scrolling]
history = 50000

[font]
normal = { family = "JetBrainsMono NFM Light", style = "Regular" }
bold = { family = "JetBrainsMono NFM", style = "Bold" }
italic = { family = "JetBrainsMono NFM Light", style = "Italic" }
bold_italic = { family = "JetBrainsMono NFM", style = "Bold Italic" }
size = 11.0

[colors]
# defined in imported theme

[cursor]
style = { shape = "Beam", blinking = "Off" }
vi_mode_style = { shape = "Underline", blinking = "On" }

[terminal]

[mouse]

[hints]

[keyboard]
bindings = [
    { key = "Escape", mods = "Shift", action = "ToggleViMode" },
    { key = "Enter", mods = "Shift", action = "SpawnNewInstance" },
]



